apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - component.yaml
  - workload.yaml
  - thunder-20260421-5.yaml
  - release-binding.yaml
  - release-binding-staging.yaml
  - release-binding-prod.yaml
