apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: thunder-githops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ayeshajay/thunder-githops  # TODO: update to actual repo URL
  ref:
    branch: demo-v1
