apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: thunderid
  namespace: thunderid
  annotations:
    openchoreo.dev/description: "WSO2 Thunder Identity Management Service"
    openchoreo.dev/display-name: "Thunder"
spec:
  owner:
    projectName: identity-platform
  componentType:
    kind: ClusterComponentType
    name: deployment/thunderid
  parameters:
    image: "ghcr.io/ayeshajay/thunderid:v0.38.0-hotfix-1"
    runtime:
      imagePullPolicy: "Always"
      gate:
        clientBase: "/gate"
      console:
        clientBase: "/console"
        clientId: "CONSOLE"
        scopes: '["openid", "profile", "email", "system"]'
      dbType: "sqlite"
      dbStorageSize: "1Gi"
