apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - component.yaml
  - workload.yaml
  - releases/thunderid-20260515-3.yaml
  - release-binding.yaml
  # - release-binding-staging.yaml
  # - release-binding-prod.yaml
