apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: thunderid-prod
  namespace: thunderid
spec:
  owner:
    componentName: thunderid
    projectName: identity-platform
  environment: production
  releaseName: thunderid-20260421-7
  state: Active
  componentTypeEnvironmentConfigs:
    replicas: 3
    endpointVisibility: "external"
    serverPublicUrl: "http://production-thunderid-thunderid.openchoreoapis.demo:19080"
    gateClientHostname: "production-thunderid-thunderid.openchoreoapis.demo"
    resourceRequestsCpu: "500m"
    resourceRequestsMemory: "512Mi"
    resourceLimitsCpu: "1000m"
    resourceLimitsMemory: "1Gi"
