apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: thunderid-staging
  namespace: thunderid
spec:
  owner:
    componentName: thunderid
    projectName: identity-platform
  environment: staging
  releaseName: thunderid-20260421-7
  state: Active
  componentTypeEnvironmentConfigs:
    replicas: 1
    endpointVisibility: "external"
    serverPublicUrl: "http://staging-thunderid-thunderid.openchoreoapis.demo:19080"
    gateClientHostname: "staging-thunderid-thunderid.openchoreoapis.demo"
    resourceRequestsCpu: "100m"
    resourceRequestsMemory: "128Mi"
    resourceLimitsCpu: "500m"
    resourceLimitsMemory: "512Mi"
